project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
   path('admin/', admin.site.urls),
   path('pages/', include('django.contrib.flatpages.urls')),
   path("accounts/", include("allauth.urls")),  # Оставили только allauth
   path('news/', include('commonapp.urls_news')),
   path('articles/', include('commonapp.urls_articles')),
   path('subscriptions/', include('commonapp.url_subs'))
]

project/commonapp/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Товар для нашей витрины 
class New(models.Model):
    # ARTICLE = 'AR'
    # NEW = 'NE'
    # AVAILABLE_TYPES = ((ARTICLE, 'Статья'), (NEW, 'Новость'))
    title = models.CharField(
        max_length=50,
        unique=True, # названия товаров не должны повторяться
    )
    text = models.TextField()
    type = 'Новость'
    made_at = models.DateTimeField(
        auto_now=True,)
    # поле категории будет ссылаться на модель категории
    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='News', # все продукты в категории будут доступны через поле products
    )

    # type = models.CharField(max_length=2, choices=AVAILABLE_TYPES, default=NEW)

    def __str__(self):
        return self.title
    # date = models.CharField(auto_now_add=datetime.strftime())
    def get_absolute_url(self):
        return reverse('new_detail', args=[str(self.id)])   # def __str__(self):
    #     return f'{self.title.title()}: {self.text[:20]}'

class Article(models.Model):
    # ARTICLE = 'AR'
    # NEW = 'NE'
    # AVAILABLE_TYPES = ((ARTICLE, 'Статья'), (NEW, 'Новость'))
    title = models.CharField(
        max_length=50,
        unique=True, # названия товаров не должны повторяться
    )
    text = models.TextField()
    type = 'Статья'
    made_at = models.DateTimeField(
        auto_now=True,)
    # поле категории будет ссылаться на модель категории
    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='Articles', # все продукты в категории будут доступны через поле products
    )

    # type = models.CharField(max_length=2, choices=AVAILABLE_TYPES, default=NEW)

    def __str__(self):
        return self.title
    # date = models.CharField(auto_now_add=datetime.strftime())
    def get_absolute_url(self):
        return reverse('article_detail', args=[str(self.id)])   # def __str__(self):
    #     return f'{self.title.title()}: {self.text[:20]}'

# Категория, к которой будет привязываться товар
class Category(models.Model):
    # названия категорий тоже не должны повторяться
    name = models.CharField(max_length=100, unique=True) 

    def __str__(self):
        return self.name.title()
    
class Subscription(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )
    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )

project/templates/article.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

<!-- Название у нас будет Product -->
{% block title %}
Article
{% endblock title %}

<!-- В контенте на странице мы выводим сам товар, идентификатор которого был передан в url -->
{% block content %}
<h1>Статья</h1>
<h1>{{ article.title }}</h1>
<h3>Дата создания:</h3>
<h3>{{ article.made_at|date:'M d Y' }}</h3>
<h1>{{ article.text|censor }}</h1>

{% endblock content %}

project/templates/articles.html
{% extends 'flatpages/default.html' %}

{% load custom_tags %}
{% load custom_filters %}

<!-- Название у нас будет products -->
{% block title %}
Articles
{% endblock title %}

<!-- В контенте на странице мы выводим все товары -->
{% block content %}
   <h1>Все товары</h1>
   <h3>{{ time_now|date:'M d Y' }}</h3>
   <h3>Количество Статей:</h3><h3> {{ news|length }} </h3>
  
    <form action="" method="get">
    {{ filterset.form.as_p }}
    <input type="submit" value="Найти" />
    </form>
  
   <hr>



   {% if articles %}
       <table>
           <tr>
               <td>Название</td>
               <td>Описание</td>
               <td>Дата создания</td>
               <td>Тип</td>
               <td>Категория</td>
               <td>ID</td>
               {% if perms.commonapp.change_article or perms.commonapp.delete_article %}
               <td>Действия</td>
               {% endif %}
           </tr>
          
           <!-- Для каждого товара будете генерироваться новая строчка,
           т.е. новый HTML код, который указан в теле цикла.
           При этом сам цикл работает точно так же, как и в Python.
           product — переменная цикла, т.е. наш товар полученный из списка -->
           {% for i in articles %}
           <tr>
               <td>{{ i.title}}</td>
               <td>{{ i.text|truncatechars:20|censor }}</td>
               <td>{{ i.made_at|date:'M d Y'}}</td>
               <td>{{ i.type }}</td>
               <td>{{ i.category.name }}</td>
               <td>{{ i.id }}</td>
               <td>               {% if perms.simpleapp.change_product %}
                <a href="{% url 'article_update' pk=i.id %}">Изменить</a>
                {% endif %}
                {% if perms.simpleapp.delete_product %}
                <a href="{% url 'article_delete' i.id %}">Удалить</a>
                {% endif %}
               </td>
           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Новостей нет!</h2>
   {% endif %}


   {% if page_obj.has_previous %}
       <a href="?{% url_replacepage=1}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replacepage=page_obj.previous_page_number }">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?{% url_replacepage= page_obj.next_page_number }">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replacepage= page_obj.paginator.num_pages} ">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}

   {% endif %}  


  

{% endblock content %}

project/templates/new.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

<!-- Название у нас будет Product -->
{% block title %}
New
{% endblock title %}

<!-- В контенте на странице мы выводим сам товар, идентификатор которого был передан в url -->
{% block content %}
<h1>Новость</h1>
<h1>{{ new.title }}</h1>
<h3>Дата создания:</h3>
<h3>{{ new.made_at|date:'M d Y' }}</h3>
<h1>{{ new.text|censor }}</h1>

{% endblock content %}

project/templates/new_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление товара</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удалить "{{ object.title }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

project/templates/new_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Новость</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

project/templates/new_search.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Новость</h1>
<hr>
<form action="" method="get">
    {{ filterset.form.as_p }}
    <button type="button">
        <a href="{% url 'new_list' %}">Click here!</a>
    </button>
    <button type="submit">Click Me!</button>
    </form>
</form>
{% endblock content %}

project/templates/news.html
{% extends 'flatpages/default.html' %}

{% load custom_tags %}
{% load custom_filters %}

<!-- Название у нас будет products -->
{% block title %}
News
{% endblock title %}

<!-- В контенте на странице мы выводим все товары -->
{% block content %}
   <h1>Все товары</h1>
   <h3>{{ time_now|date:'M d Y' }}</h3>
   <h3>Количество новостей:</h3><h3> {{ news|length }} </h3>
  
    <form action="" method="get">
    {{ filterset.form.as_p }}
    <input type="submit" value="Найти" />
    </form>
  
   <hr>



   {% if news %}
       <table>
           <tr>
               <td>Название</td>
               <td>Описание</td>
               <td>Дата создания</td>
               <td>Тип</td>
               <td>Категория</td>
               <td>ID</td>
               {% if perms.commonapp.change_new or perms.commonapp.delete_new %}
               <td>Действия</td>
               {% endif %}
           </tr>
          
           <!-- Для каждого товара будете генерироваться новая строчка,
           т.е. новый HTML код, который указан в теле цикла.
           При этом сам цикл работает точно так же, как и в Python.
           product — переменная цикла, т.е. наш товар полученный из списка -->
           {% for i in news %}
           <tr>
               <td>{{ i.title}}</td>
               <td>{{ i.text|truncatechars:20|censor }}</td>
               <td>{{ i.made_at|date:'M d Y'}}</td>
               <td>{{ i.type }}</td>
               <td>{{ i.category.name }}</td>
               <td>{{ i.id }}</td>
               <td>
               {% if perms.simpleapp.change_product %}
               <a href="{% url 'new_update' pk=i.id %}">Изменить</a>
               {% endif %}
               {% if perms.simpleapp.delete_product %}
               <a href="{% url 'new_delete' i.id %}">Удалить</a>
               {% endif %}
               </td>
           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Новостей нет!</h2>
   {% endif %}


   {% if page_obj.has_previous %}
       <a href="?{% url_replacepage=1}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replacepage=page_obj.previous_page_number }">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?{% url_replacepage= page_obj.next_page_number }">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replacepage= page_obj.paginator.num_pages} ">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}

   {% endif %}  


  

{% endblock content %}

project/templates/subscriptions.html
{% extends 'flatpages/default.html' %}

{% block title %}
Subscriptions
{% endblock title %}

{% block content %}
    {% for category in categories  %}
        <p>
            {{ category.name }}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="category_id" value="{{ category.id }}" />

                {% if category.user_subscribed %}
                    <button disabled>Подписаться</button>
                    <button name="action" value="unsubscribe">Отписаться</button>
                {% else %}
                    <button name="action" value="subscribe">Подписаться</button>
                    <button disabled>Отписаться</button>
                {% endif %}
            </form>
        </p>
    {% endfor %}
{% endblock content %}